// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide":{"path":"guide","id":"docs/guide","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"docs/html":{"path":"html","id":"docs/html","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/zhaoqianyu/Documents/project/web-engineering/node_modules/.pnpm/dumi@2.3.8_@babel+core@7.24.6_@swc+helpers@0.5.1_@types+node@20.13.0_eslint@9.5.0_jest@29.7.0_4c2h4sazxrjthlvxy3nglmdmji/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/zhaoqianyu/Documents/project/web-engineering/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/zhaoqianyu/Documents/project/web-engineering/node_modules/.pnpm/dumi@2.3.8_@babel+core@7.24.6_@swc+helpers@0.5.1_@types+node@20.13.0_eslint@9.5.0_jest@29.7.0_4c2h4sazxrjthlvxy3nglmdmji/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide': React.lazy(() => import(/* webpackChunkName: "docs__guide.md" */'/Users/zhaoqianyu/Documents/project/web-engineering/docs/guide.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/zhaoqianyu/Documents/project/web-engineering/docs/index.md')),
'docs/html': React.lazy(() => import(/* webpackChunkName: "docs__html.md" */'/Users/zhaoqianyu/Documents/project/web-engineering/docs/html.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/zhaoqianyu/Documents/project/web-engineering/node_modules/.pnpm/dumi@2.3.8_@babel+core@7.24.6_@swc+helpers@0.5.1_@types+node@20.13.0_eslint@9.5.0_jest@29.7.0_4c2h4sazxrjthlvxy3nglmdmji/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
