// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhaoqianyu/Documents/project/web-engineering/node_modules/.pnpm/dumi@2.3.8_@babel+core@7.24.6_@swc+helpers@0.5.1_@types+node@20.13.0_eslint@9.5.0_jest@29.7.0_4c2h4sazxrjthlvxy3nglmdmji/node_modules/dumi/theme-default/slots/ContentFooter/index.js';
